# Generated by Django 3.1.2 on 2021-04-08 15:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210408_2114'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('onjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
